name: Quick Discord Notification

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches:
      - '*'
  issues:
    types: [opened, edited, milestoned]

jobs:
  send_noti:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1.13.1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ github.event_name }} -- ${{ env.BRANCH_NAME }}
          color: 0xff3366

